---
title: Чат-бот
hero_image: images / chatbot.png
description: Дізнайтеся, як програмувати власного робота, що розмовляє!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: фіолетовий
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, дизайн-0, програмування-1, фізичні обчислення-0, виробництво-0, спільноти-0
interests: ''
technology: подряпати
site_areas: проекти
technologies: подряпати
hardware: ''
software: подряпати
version: 4.1.0
last_tested: 01.01.2017
steps:
  - 
    title: Вступ
  - 
    title: Те, що вам знадобиться
  - 
    title: Ваш чат-бот
  - 
    title: Чат-бот, що розмовляє
  - 
    title: Прийняття рішень
  - 
    title: Зміна розташування
  - 
    title: 'Challenge: завершення чат-боту'
