---
title: Chatbot
hero_image: images / chatbot.png
description: Tìm hiểu cách lập trình robot nói chuyện của riêng bạn!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: màu tím
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, thiết kế-0, lập trình-1, phys-comp-0, sản xuất-0, cộng đồng-0
interests: ''
technology: vết trầy
site_areas: dự án
technologies: vết trầy
hardware: ''
software: vết trầy
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Chatbot của bạn
  - 
    title: Chatbot trò chuyện
  - 
    title: Ra quyết định
  - 
    title: Thay đổi vị trí
  - 
    title: 'Thách thức: kết thúc chatbot của bạn'
