---
title: Chatbot
hero_image: images / chatbot.png
description: Öz söhbət edən robotunuzu necə proqramlaşdırmağı öyrənin!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: bənövşəyi
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: cızıq
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Giriş
  - 
    title: Nə lazımdır?
  - 
    title: Sizin şifrəniz
  - 
    title: Konuşan bir sohbet dili
  - 
    title: Qərar qəbul etmə
  - 
    title: Yerin dəyişdirilməsi
  - 
    title: 'Çağırış: chatbotunuzu bitirin'
