---
title: ചാറ്റ്ബോട്ട്
hero_image: images / chatbot.png
description: നിങ്ങളുടെ സ്വന്തം സംസാരിക്കുന്ന റോബോട്ട് എങ്ങനെ പ്രോഗ്രാം ചെയ്യാം എന്ന് അറിയുക!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: വയലറ്റ്
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: സ്ക്രാച്ച്
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: ആമുഖം
  - 
    title: നിങ്ങൾക്ക് എന്ത് വേണം
  - 
    title: നിങ്ങളുടെ ചാറ്റ് ബോട്ട്
  - 
    title: സംസാരിക്കുന്ന ചാറ്റ്ബോട്ട്
  - 
    title: തീരുമാനങ്ങൾ എടുക്കൽ
  - 
    title: സ്ഥാനം മാറ്റുന്നു
  - 
    title: 'വെല്ലുവിളി: നിങ്ങളുടെ ചാറ്റ് ബോട്ട് പൂർത്തിയാക്കുക'
