---
title: chatbot
hero_image: Kuvien / chatbot.png
description: Opi ohjelmoimaan oma puhuva robotti!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violetti
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
interests: ''
technology: naarmu
site_areas: hankkeet
technologies: naarmu
hardware: ''
software: naarmu
version: 4.1.0
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: Mitä tarvitset
  - 
    title: Chatbotisi
  - 
    title: Puhuva chatbot
  - 
    title: Tehdä päätöksiä
  - 
    title: Sijainnin muuttaminen
  - 
    title: 'Haaste: viimeistele chatbot'
