---
title: Robot Parlanchín
hero_image: images/chatbot.png
description: ¡Aprende a programar tu propio robot parlante!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: ''
technology: scratch
site_areas: projects
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Introducción
- title: Tu robot parlanchín
- title: Un robot que habla
- title: Tomar decisiones
- title: Cambiar la ubicación
- title: "Desafío: Crea tu propio robot parlanchín"