---
title: Robot Parlanchín
hero_image: images/chatbot.png
description: ¡Aprende a programar tu propio robot parlante!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Tu robot parlanchín
- title: Un robot que habla
- title: Tomar decisiones
- title: Cambiar la ubicación
- title: "Desafío: Crea tu propio robot parlanchín"

