---
title: SgwrsBot
hero_image: images/chatbot.png
description: Dysga sut i raglenni robot dy hunan sydd yn siarad!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
- title: Cyflwyniad
- title: Dy SgwrsBot
- title: SgwrsBot sy'n siarad
- title: Gwneud penderfyniadau
- title: Newid lleoliad
- title: 'Her: Gwneud dy SgwrsBot dy hunan'

