---
title: SprechBot
hero_image: images/chatbot.png
description: In diesem Projekt wirst Du lernen, wie Du Deinen eigenen sprechenden Roboter programmieren kannst!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: Scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Dein SprechBot
  - 
    title: Ein sprechender Roboter
  - 
    title: Entscheidungen treffen
  - 
    title: Ort ändern
  - 
    title: 'Herausforderung: Mache Deinen eigenen SprechBot'
  - 
    title: 'Challenge: Vervollständige deinen Chatbot'
