---
title: Robot parlant
hero_image: images/chatbot.png
description: Apprends à programmer ton propre robot qui parle!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Votre robot parlant
- title: Un chatbot parlant
- title: Prendre des décisions
- title: Changement d'emplacement
- title: "Défi : Créer votre propre chatbot"

