---
title: ChatterBot
hero_image: images/chatbot.png
description: Impara a programmare il tuo robot parlante!
original_url: https://projects.raspberrypi.org/en/projects/chatbot
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
- title: Introduzione
- title: Il tuo chatterbot
- title: Un chatterbot parlante
- title: Prendere decisioni
- title: Cambia posizione
- title: "Sfida: Crea il tuo chatterbot"

